name: reformedcoder
favicon: null
layout_spectrum: 0.6625
typography_spectrum: 0.65981
title: Brian Rountree is a reformed coder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d35400'
    - '#f2ddd1'
    - '#3498db'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
